#include <iostream>

using std::string; //this so that i don't have to write 3 lines below
				   // std::string every time. Just for readability.

//! PART A :

// everything inside this class is private by default:
class Employee {
	string Name;
	string Company;
	int Age;
};

//which is exactly the same as this situation:
class Employee {
private:	
	string Name;
	string Company;
	int Age;
};

//? SCENARIO B:
//so in order to be able to access the members of the class i need to do:
class Employee {
public:	
	string Name;
	string Company;
	int Age;

	// a "class method" is moreover a function inside the class.
	void Intoduce_Yourself(){
		std::cout << "Name - " << Name << std::endl;
		std::cout << "Company - " << Company << std::endl;
		std::cout << "Age - " << Age << std::endl;
	}
	// the class method kinda represents a behavior of our object we can provoke whenever we want.
};

int main()
{
	int number;
	//and the same way that we create the normal variables, we do also the object of the class we want:
	Employee empl1; //a "variable" of type Employee -> this is going to be an object of the above class.
	//if the members of the struct are not public, i can not access them with empl1. 
	// but if the members are public (SCENARIO B) i can now access them and assign values:
	empl1.Name = "Mary Kate";
	empl1.Company = "42 Heilbronn";
	empl1.Age = 23;
	// ... to access the attributes of the struct, but this doesn't happen because in c++ by default all the "members" of the class are private.
	//how to provoke the "behavior" of our employee, meaning to make him introduce himself:
	empl1.Intoduce_Yourself();

	Employee emp2; //a constructor is invoked
	Employee emp3; //a constructor is invoked

}

//! PART B: CONSTRUCTORS
/*
In c++ we have 3 access modifiers:
-	private: it can not be accessible outside of the class
-	public: i can access the members of the class even outside of the class (for example in my main function)
-	protected: something between private and public, that has specific rules.
				the derived class can also accessthe protected attributes

A constructor is a special type of method that is invoked each time an object of the class is created. 

Default constructor: is automatically generated by the compiler. 
If I don't create a constructor of my own the compiler is going to give me one. this is the "default" constructor.

A constructor is like a "method", so like a function, but:
	RULES of a constructor:
	- it does not have a return type
	- a constructor has the same name as the class he belongs to
	- the constructor must be PUBLIC (there are exceptions)

The moment we create a constructor of our own, that means it destroys the default constructor.
*/

class Employee {
public:	
	string Name;
	string Company;
	int Age;

	// a "class method" is moreover a function inside the class.
	void Intoduce_Yourself(){
		std::cout << "Name - " << Name << std::endl;
		std::cout << "Company - " << Company << std::endl;
		std::cout << "Age - " << Age << std::endl;
	}

	//? how to create a constructor:
	Employee(string name, string company, int age) {
		//the constructor constructs the object here, assigning the given values:
		Name = name;
		Company = company;
		Age = age;
	}
};

int main()
{
	/*
	Now that i have the constructor, instead of doing:
	Employee empl1;
	empl1.Name = "Mary Kate";
	empl1.Company = "42 Heilbronn";
	empl1.Age = 23;
	empl1.Intoduce_Yourself();
	*/
	//I can just do:
	Employee empl1 = Employee("Mary Kate", "42 Heilbronn", 23); //the constructor receives the parameters here
	empl1.Intoduce_Yourself();

	// So that if I had multiple employees, I wouldn't have to repeat every time the 3 lines
	// for each one of them. So I can just say:
	Employee empl2 = Employee("John", "Amazon", 35);
	empl2.Intoduce_Yourself();

	//and same for employee3, 4, 5 and so on...

}


//! PART C: ENCAPSULATION

/*
	Encapsulation: budling or tying together data, and methods that operate on that data. SO that they are grouped together on a class.
	With the purpose of preventing anyone outside of my class to be able to directly access the data of the class, intereact with it or modify it.
	We don't want that to happen directly. We want to provide our own way for that interaction.
	for the we use SETTERS and GETTERS, which are just class methods (functions)
*/

class Employee {
private:
	// now these 3 variables are "encapsulated":
	string Name;
	string Company;
	int Age;
public:	
	
	// For every "encapsulated variable" we need a setter and a getter:

	// Setter for Name:
	void setName(string name) {
		Name = name;
	}
	// Getter for Name:
	string getName() {
		return Name;
	}

	// Setter for Company:
	void setCompany(string company) {
		Company = company;
	}
	// Getter for Company:
	string getCompany() {
		return Company;
	}
	
	// Setter for Age:
	void setAge(int age) {
		if (age >= 18)
			Age = age;
	}
	// Getter for Age:
	int getAge() {
		return Age;
	}
	
	void Intoduce_Yourself() {
		std::cout << "Name - " << Name << std::endl;
		std::cout << "Company - " << Company << std::endl;
		std::cout << "Age - " << Age << std::endl;
	}

	//constructor:
	Employee(string name, string company, int age) {
		Name = name;
		Company = company;
		Age = age;
	}

};

int main()
{
	Employee empl1 = Employee("Mary Kate", "42 Heilbronn", 23); 
	empl1.Intoduce_Yourself();

	Employee empl2 = Employee("John", "Amazon", 35);
	empl2.Intoduce_Yourself();

	/* So now although the Name, Company and Age are private attributes, and I wouldn't be able to 
		modify them doing 
			empl1.Name = "Mary Kate";
			empl1.Company = "42 Heilbronn";
			empl1.Age = 23;
		I can now call the getters and setters:
	*/
	// So if i do: 
	empl1.setAge(30); // then the attribute Age of empl1 will be indeed changed.
	// But if I do:
	empl1.setAge(15); //it will not work, because I'm checkind if >= 18 in the setter.

}
/*
	so now with the encapsulation, whoever wants to have access to my class' variables 
	(name, Company, Age)	the need to use the methods of the class that i "expose", 
	meaning the setters and getters.
*/


//! PART D: ABSTRACTION

/*
	Abstraction:
	"Hiding complex things behind a procedure that makes those things look simple"
	In OPP We simulate the behavior of interface using abstract classes
*/

//! We use an "abstract class":
class AbstractEmployee {
	// pure virtual function:
	virtual void AskForPromotion() = 0;
	// that means that whichever class calls this contract (abstract class), needs 
	// to provide implemetation for the method AskForPromotion. Like the class above:
	//? we use the "virtual .... = 0;" to make the function AskForPromotion obgigatory
	//? so that any class that calls this abstract class MUST provide implementation
	//? for the AskForPromotion method.
};

// So now, instead of starting the class as:
// class Employee {
// we do:
class Employee:AbstractEmployee { //which means that this class is bound to "AskForPromotion"
//	so in this case, our Employee is "inheriting" from our AbstractEmployee
// so now it means that if I create an "Employee" object, I can invoke the method AskForPromotion.
// doing in my main for example: empl1.AskForPromotion();
private:
	string Name;
	string Company;
	int Age;
public:	
	void setName(string name) {
		Name = name;
	}
	string getName() {
		return Name;
	}
	void setCompany(string company) {
		Company = company;
	}
	string getCompany() {
		return Company;
	}
	void setAge(int age) {
		if (age >= 18)
			Age = age;
	}
	int getAge() {
		return Age;
	}
	
	void Intoduce_Yourself() {
		std::cout << "Name - " << Name << std::endl;
		std::cout << "Company - " << Company << std::endl;
		std::cout << "Age - " << Age << std::endl;
	}

	//constructor:
	Employee(string name, string company, int age) {
		Name = name;
		Company = company;
		Age = age;
	}

	//! the method that the abstract class needs:
	void AskForPromotion() {
		if (Age > 30)
			std::cout << Name << " got promoted!" << std::endl;
		else
			std::cout << Name << " sorry no Promotion for you!" << std::endl;
	}
};

int main()
{
	Employee empl1 = Employee("Mary Kate", "42 Heilbronn", 23); 
	Employee empl2 = Employee("John", "Amazon", 35);

	// So now I can do: 
	empl1.AskForPromotion();
	empl2.AskForPromotion();
	// and indeed for me it will print "sorry no promotion" but for John it will say
	// "got promoted"
}


//! PART E: INHERITANCE
/*
	A derived/child class inherits all the attributes and methods of the parent class, 
	and it can have additional attributes and/or methods of each own, that the parent
	class doesn't have.
	"subclass" or "derived class"
	"base class" or "parent class" or "super class";
*/

// the "abstract class":
class AbstractEmployee {
	// pure virtual function:
	virtual void AskForPromotion() = 0;
};

class Employee:AbstractEmployee { //which means that this class is bound to "AskForPromotion"
//	so in this case, our Employee is "inheriting" from our AbstractEmployee
// so now it means that if I create an "Employee" object, I can invoke the method AskForPromotion.
// doing in my main for example: empl1.AskForPromotion();
private:
	string Name;
	string Company;
	int Age;
public:	
	void setName(string name) {
		Name = name;
	}
	string getName() {
		return Name;
	}
	void setCompany(string company) {
		Company = company;
	}
	string getCompany() {
		return Company;
	}
	void setAge(int age) {
		if (age >= 18)
			Age = age;
	}
	int getAge() {
		return Age;
	}
	
	void Intoduce_Yourself() {
		std::cout << "Name - " << Name << std::endl;
		std::cout << "Company - " << Company << std::endl;
		std::cout << "Age - " << Age << std::endl;
	}

	//constructor:
	Employee(string name, string company, int age) {
		Name = name;
		Company = company;
		Age = age;
	}

	// the method that the abstract class needs:
	void AskForPromotion() {
		if (Age > 30)
			std::cout << Name << " got promoted!" << std::endl;
		else
			std::cout << Name << " sorry no Promotion for you!" << std::endl;
	}
};

//! the subclass that inherits from the parent class "Employee":
class Developer:Employee {
public:
	string FavProgrLang;
	//now this subclass needs a constructor of its own:
	Developer(string name, string company, int age, string fpl)
		:Employee(name, company, age) //we do this because there is already a constructor for these 3 attributes, on the parent class "Employee"
	{
		FavProgrLang = fpl;
	}
	// let's create a new method on the subclass:
	void FixBug() {
		std::cout << getName() << " fixed bug using " << FavProgrLang << std::endl;
	}
	//? but if the "Name" attribute of the Employee class was "protected" instead of
	//? "private" we could access directly the Name value from the subclass and do:
	// void FixBug() {
	// 	std::cout << Name << " fixed bug using " << FavProgrLang << std::endl;
	// }
	//now is red, but if it was "protected" it wouldn't be
};

int main()
{
	Employee empl1 = Employee("Mary Kate", "42 Heilbronn", 23); 
	Employee empl2 = Employee("John", "Amazon", 35);

	// and now we can create an object of the subclass Developer:
	Developer d = Developer("Saldina", "Youtube", 25, "C++");
	//and we can call the method of the class like:
	d.FixBug(); //which prints: Saldina fixed bug using C++
}

// when the class is initialized as:
class Developer: Employee {};
// the inheritance is by default private. 
// and the the Developer Class can not access the methods or attributes of the parent class (Employee)
// in order to do:
d.AskForPromotion();
// But if we change the inheritance to public, initializing the class as:
class Developer: public Employee {};
// now we can call actually the methods or attributes of the parent class and do:
d.AskForPromotion();




//! PART F: POLYMORPHISM
/*
	= "The ability of an object or a method to have many forms"

	the most common use of polymorphism is when a parent class 
	reference is used to refer to a child class object
*/


class AbstractEmployee {
	// pure virtual function:
	virtual void AskForPromotion() = 0;
};

class Employee:AbstractEmployee {
protected:
	string Name;
private:
	string Company;
	int Age;
public:	
	void setName(string name) {
		Name = name;
	}
	string getName() {
		return Name;
	}
	void setCompany(string company) {
		Company = company;
	}
	string getCompany() {
		return Company;
	}
	void setAge(int age) {
		if (age >= 18)
			Age = age;
	}
	int getAge() {
		return Age;
	}

	//constructor:
	Employee(string name, string company, int age) {
		Name = name;
		Company = company;
		Age = age;
	}

	// the method that the abstract class needs:
	void AskForPromotion() {
		if (Age > 30)
			std::cout << Name << " got promoted!" << std::endl;
		else
			std::cout << Name << " sorry no Promotion for you!" << std::endl;
	}

	//! new method here to show polymorphism:
	virtual void Work() { //! the virtual practically says: can you please check if there is implemetantion of this function in my derived classes? If yes, please execute that, and not this here:
	std::cout << Name << " is checking emails" << std::endl;
	}
};

// first subclass that inherits from the parent class "Employee":
class Developer: public Employee {
public:
	string FavProgrLang;
	//now this subclass needs a constructor of its own:
	Developer(string name, string company, int age, string fpl)
		:Employee(name, company, age) //we do this because there is already a constructor for these 3 attributes, on the parent class "Employee"
	{
		FavProgrLang = fpl;
	}
	void FixBug() {
		std::cout << Name << " fixed bug using " << FavProgrLang << std::endl;
	}
	//! same name of method, as the one in the parent class, but different implementation:
	void Work() {
	std::cout << Name << " is writing code in " << FavProgrLang << std::endl;
	}
};

// second subclass that inherits from the parent class "Employee":
class Teacher: public Employee {
public:
	string Subject;
	//now this subclass needs a constructor of its own:
	Teacher(string name, string company, int age, string subject)
		:Employee(name, company, age) //we do this because there is already a constructor for these 3 attributes, on the parent class "Employee"
	{
		Subject = subject;
	}
	//! same name of method, as the one in the parent class, but different implementation:
	void Work() {
	std::cout << Name << " is preparing " << Subject << "lesson" << std::endl;
	}
};

int main()
{
	Developer d = Developer("Saldina", "Youtube", 25, "C++");
	Teacher t = Teacher("John", "School", 40, "History");
	
	//and now although there is a method "work" on the parent class Employee, 
	// the next two, will have indeed different result:
	d.Work(); //output: Saldina is writing code in C++
	t.Work(); //output: John is preparing History lesson

	//? :	 the most common use of polymorphism is when a parent class 
	//?   	 reference is used to refer to a child class object
	Employee *e1 = &d; 
	Employee *e2 = &t;
	// so a pointer of a base class can hold reference to derived class object.

	// And this way, we can now call:
	e1->Work(); //output: Saldina is writing code in C++
	e2->Work();//output: John is preparing History lesson
	// But if the Work method in the base class Employee was not virtual (line 473)
	// Then the output for both Saldina and John would be: is checking emails
}



//! ORTHODOX CANONICAL FORM
 /*
	the key components of the Orthodox Canonical Form:

	1) Default Constructor: This constructor initializes an object with default values. 
		It's typically invoked when an object is created without any arguments.

	2) Copy Constructor: This constructor creates a new object by copying the contents of 
		an existing object of the same type. It's invoked when an object is initialized with 
		another object of the same type or when an object is passed by value.

	3) Copy Assignment Operator: This operator assigns the contents of one object to another 
		object of the same type. It's invoked when an object is assigned the value of another
		object of the same type using the assignment operator (=).

	4) Move Constructor: This constructor creates a new object by moving the resources (such 
		as dynamically allocated memory) from an existing object of the same type. It's invoked 
		when an object is initialized with an rvalue reference.

	5) Move Assignment Operator: This operator assigns the contents of one object to another 
	object of the same type by moving resources from one object to another. It's invoked when 
	an object is assigned the value of an rvalue reference using the assignment operator (=).

	6) Destructor: This function is responsible for releasing any resources allocated by the 
	class when an object is destroyed. It's invoked automatically when an object goes out of 
	scope or is explicitly deleted.
 */

// TODO : FROM INTRA VIDEOS 
---------------------------------

//"this" is a pointer on a current instance

class Sample {

public:

	char	a1;
	int		a2;
	float	a3;

	Sample( char p1, int p2, float p3);
	~Sample( void );
}

//? The syntax of the constructor from the intra video:

Sample::Sample( char p1, int p2, float p3 ) : a1(p1), a2(p2), a3(p3) {

	std::cout << "Constructor called" << std::endl;
}



//! If I write a member function that doesn't modify the instance of my class, I should 
//! always define it as const. Like:

class Sample {

public:

	char	a1;
	int		a2;
	float	a3;

	Sample( char p1, int p2, float p3);
	~Sample( void );

	void	bar(void) const;
};

//and then the definition of the bar:
void	Sample::bar(void) const {

	std::cout << "Hello from bar method" << std::endl;
}

//? The syntax of the constructor from the intra video:

Sample::Sample( char p1, int p2, float p3 ) : a1(p1), a2(p2), a3(p3) {

	std::cout << "Constructor called" << std::endl;
}


//! in c++:
//!		the scope of a struct is public by default
//!		the scope of a class is private by default

// Two different instances of a class are not physically equivalent (different addresses), but
// They are "structurally" same (exactly same content) if they have been both just initialized.

// a static attribute or method in a class is a "non-member function/attribute" 


//! new and delete for dynamic allocation of objects

//for one object:
int main() {
	Student *mk = new Student("mevangel");
	// ...
	delete mk;
}

//for array of objects:
int main ()
{
	Sample* pointer_to_array = new Sample[42];
	//...
	delete [] pointer_to_array; //! i must not forget the []
}


//! References: 

// "They're just an alias for existing variable"
// "It's a pointer that is constant, always unreferenced and never void"


//! Ad-hoc polymorphism or "Function Overload":
// allows to define many functions with the same name, which take different parameters

//? 1) Overload of the insertion operator:"

struct YoutubeChannel {

	string Name;
	int SubscribersCount;

	YoutubeChannel(string name, int count) {
		Name = name;
		SubscribersCount = count;
	}
}

ostream& operator<<(ostream COUT, YoutubeChannel& ytChannel) {
	COUT << "Name: " << ytChannel.Name << endl;
	COUT << "Subscribers: " << ytChannel.SubscribersCount << endl;
	return COUT;
}

int main()
{
	YoutubeChannel yt1; YoutubeChannel("CodeBeauty", 75000);
	YoutubeChannel yt1; YoutubeChannel("Second Channel", 80000);

	//without the above operation overload, it would be impossible to do sometihing like:
	cout << yt1; //(insertion operator)
	//But now that i "overloaded" the operator "<<" i can actually do the above.
	// And it would have the same result, also if I would do:
	operator<<(cout, yt1); //it's like calling a global function
}

//! ORTHODOX CANONICAL FORM:

#include <iostream>

class Sample {

	private:
		int _foo;

	public:

		// A set of constructors:

		// Default constructor:
		Sample(void);										//! canonical

		Sample(int const n);

		// Copy constructor:
		Sample(Sample const & src);							//! canonical
		// it creates a new instance os a Sample

		~Sample();											//! canonical

		// Copy assignment operator (operator overload)
		Sample & operator=( Sample const & rhs );			//! canonical
		// we only have an "update" of the current instance. Doesn't return a new instance like the copy constructor.

		int getFoo(void) const ;
};

std::ostream & operator<<(std::ostream & o, Sample const & i);



// and the in the Sample.cpp:

//! 1. Default Constructor:
Sample::Sample(void) : _foo(0) {
	std::cout << "Default constructor called" << std::endl;
	return;
}

// Parameter Constructor
Sample::Sample(int const n) : _foo(n) {
	std::cout << "Parametric constructor called" << std::endl;
	return;
}

//! 2. COPY CONSTRUCTOR:
Sample::Sample(Sample const & src) {
	std::cout << "Copy constructor called" << std::endl;
	*this = src;
	return;
}

//! 3. Copy assignment operator:
Sample & Sample::operator=(Sample const & rhs) {

	std::cout << "Assignment operator called" << std::endl;

	if (this != &rhs)
		this->_foo = rhs.getFoo();

	return *this;
}

//! 4. Destructor
Sample::~Sample(void) {
	std::cout << "Destructor called" << std::endl;
	return;
}


//! EXCEPTIONS

#include <stdexcept>

void test1()
{
	try
	{
		// I do some stuff here
		if (/*there is an error*/)
		{
			throw std::exception();
		}
		else
		{
			// I do whatever i wanted
		}
	}
	// catch(const std::exception& e) //the autofilled version
	// {
	// 	std::cerr << e.what() << '\n';
	// }
	
	catch (std::exception e) // Zaz's version from the intra video
	{
		// I handle the error here
	}
}

void test4() {

	class PEBKACEException : public std::exception{
		public:
			virtual const char* what() const throw() {
				return ("Problem exists between keyboard and chair");
			}
	};

try {
	test3(); //any function that i'm calling something that could fail
}
catch (PEBKACEException& e) { //"specific catch"
	// control code
}
catch (std::exception& e) { //"generic catch"
	// control for exceptions that are like std::exception
}
catch (out_of_range& e)
{

}

//! throwing exceptions is "resource-consuming" so we shouldn't "overuse" it!
// examples of system functions that might return exceptions: new, open(), osstring


// the example from the youtube video that helped more:
#include <iostream>

// class custom_exception_here : public std::exception {

// 	virtual const char* what() const noexcept {
// 		return "Custom Exception";
// 	}
// };

int main() {

	std::string word = "four";

	try {
		// std::cout << word.at() << std::endl;
		// int *array = new int[9999999999999999];
		// delete [] array;
		// we can throw our own exceptions even, like:
		// throw std::exception();
		// or something more specific if we want:
		// throw std::runtime_error("problem encountered");
		// throw custom_exception_here();
		throw 4.25;
	}
	// 1st scenario that catches everything:
	// catch (...) {
	// 	std::cout << "Exception thrown!" << std::endl;
	// }
	// 2nd scenario specifically for one exception:
	catch (std::out_of_range& e) {
		std::cout << "Exception: " << e.what() << std::endl;
	}
	catch (std::exception& e) {
		std::cout << "Second catch: " << e.what() << std::endl;
	}
	catch (int code) {
		std::cout << "Error code: " << code << std::endl;
	}
	catch (...) {
		std::cout << "Default catch case!" << std::endl;	
	}
	return 0;
}


//! CASTS  -  CPP MODULE 06

int main()
{
	int a = 42;
	double b = a; //implicit converison cast: the compiler will acst it for me
	double c = (double) a; //explicit cast: i'm telling the compiler to cast it for me

	double	d = a; //implicit promotion => OK
	int		e = d; //implicit cast - demotion => hazardous !
	int		f = (int) d; //explicit cast - demotion => OK.     => i'm telling the compiler that im aware for the demotion and loss of accuraccy

	//! promotion: works either as implicit or explicit cast
	//! demotion: works only as explicit cast. Implicit doesn't compile with specific flag.
}

//! identity cast: the base value keeps the same bit after conversion in the same order.
// this particular cast of identity cast, is called REINTERPRETATION CAST

int main() {

	float a = 420.042f;

	void * b = &a; // Implicit reinterpretation cast
	void *c = (void *) &a; // Explicit reinterpretation cast
						//here we're reinterpreting the address of a float as an adress to anything. 
						// we lost in accuracy but gained in generality.

	void *d = &a; //implicit promotion => OK!
	int *e = d; //implicit cast - demotion => hazardous! //! should never do that!
	int *f = (int *) d; //explicit cast - demotion => OK. We tell the compiler that the demotion is on purpose.
}

//! We can not give a float address to an integer address, but we can give a float address to a void address, since a void * is more generic.

//! 3) Type-qualifier cast:
int main() {
	
	int	 	a = 42;

	int	const *b = &a; 					// implicit type-qualifier cast
	int const *c = (int const *) &a; 	// explicit type-qualifier cast

	int * const d = &a; 				// implicit promotion => OK
	int * e = d; 						//! implicit demotion => hell no!! 
										// the compiler will not even allow it
	int * f = (int *) d; 				// explicit demotion => OK

}

//! 3b : Upcast and downcast in c++:
{
#include <iostream>

class Parent {};
class Child1 : public Parent {};
class Child2 : public Parent {};

int main() {

	Child1 a;						//reference value

	Parent * b = &a;				// implicit reinterpretation§ cast
	Parent * c = (Parent *) &a;		// implicit reinterpretation§ cast

	Parent * d = &a;				//! implicit UPCAST => ok!
	Child1 * e = d;					//! implicit DOWNCAST => hell no! =>the compiler will not even allow it!
	Child2 * f = (Child2 *)d;		// explicit downcast => will compile, but not good practice!
}

}

//CASTS IN C++:

//! 1. static_cast:
// will prevent from cast between classes from separate hierarchy trees
{
	int a = 42;
	double b = a; //implicit promotion
	int c = b;

	int d = static_cast<int>(b); // explicit demotion (= "make b of type int")
	//the above example of 'Child2 * f = (Child2 *)d;' in c++ we write it as:
	Child2 * f = static_cast<Child2 *>(d);
	//the static cast allows us to make simple conversions, and also upcasts and downcasts, but prevents from casts between unrelated classes
}

//! 2. dynamic_cast
// it's the only one that happens in runtime and not during the compilation =>i have to implement the code to detect cases that the dynamic cast will fail
// it will only work with polymorphic instances. we use sub-type polymorphism.
{
#include <iostream>

class Parent { public: virtual ~Parent(void) {} };
class Child1 : public Parent {};
class Child2 : public Parent {};

int main() {

	Child1 a;
	Parent * b = &a; //implicit upcast => Ok!

	// explicit downcast:
	Child1 * c = dynamic_cast<Child1 *>(b);
	if ( c == NULL) //we casted it to a pointer so we can check if it's NULL for failure
		std::cout << "Conversion is NOT okay!" << std::endl;
	else
		std::cout << "Conversion is ok!" << std::endl;

	// second scenario with reference now.
	// we can not check if a reference is NULL of course, so in this case we use exceptions in c++
	try {
		Child2 & d = dynamic_cast<Child2 &>(*b); //! this will not work, so we will have the message of the exception below
		std::cout << "Conversion is okay!" << std::endl;
	}
	catch (std::bad_cast &bc) {
		std::cout << "Conversion is NOT okay: " << bc.what() << std::endl;
		return 0;
	}

}
}

//! 3. reinterpret_cast
// we can reinterpret any address with any other address
// the compiler trusts me. I am responsible for the consequences.
int main() {

	float a = 420.042f;

	void* b = &a;							//implicit promotion
	int* c = reinterpret_cast<int *>(b); 	// explicit demotion => Ok, I obey!
	int & d = reinterpret_cast<int &>(b); 	// explicit demotion => Ok, I obey!
}

//! 4. const_cast
// 
int main() {

	int a = 42;

	int const * b = &a; 					// implicit promotion ("promotion" cause "const" variables are higher)
	int * c = b;							// hell no!
	int *d = const_cast<int *>(b);			// explicit demotion! okay!
	// which was the same as above : int const *c = (int const *) &a; 	// explicit type-qualifier cast
}

//! type-cast operators
{
#include <iostream>

class Foo {

	private:
		float _v;
	
	public:
		Foo (flaot const v) : _v(v) {}

		float getV() { return this->_v; }

		operator float() { return this->_v };
		operator int() { return static_cast<int>(this->_v); }
};


int main() {
	Foo a( 420.042f );
	//and the above two operators of the class Foo allow us to do:
	float b = a;
	int c = a;

	std::cout << a.getV() << std::endl;		//prints: 420.042
	std::cout << b << std::endl;			//prints: 420.042
	std::cout << c << std::endl;			//prints: 420
}
}


//! TEMPLATE FUNCTIONS:

{

#include <iostream>

int max(int x, int y) {
	return (x>=y ? x : y); // ="if x is greater or equal than y, return x. Else return y."
}

But lets say we wwant our function to work with different types of variables.
Then we can use a "Global type" T, like:

template< typename T >
T max(T x, T y) {
	return (x>=y ? x : y);
}

or a small upgrade:

template< typename Type>
Type const & max(Type const & x, Type const & y) {
	return (x>=y ? x : y);
}
// So this way, our template function `max` can work for any type of variable (int, char, float etc) or even 
// instances of classes, as long as we have the >= operator overloaded.

int main() {
	int a = 5;
	int b = 10;

	std::cout << max<int>(a, b) << std::endl; //explicit instantiation
	std::cout << max(a, b) << std::endl; //implicit instantiation

}

//! TEMPLATE CLASSES:
// (in file `ClassName.class.tpp`) from the intra video recommendation

template < typename T >
class List {

	public:

		List<T>(T const & content) {...}

		List<T>(List<T> const & list) {...}
		
		~List<T>() {}

	private:

		T * _content;
		List<T> * _next;
}

//instanciation of the template classes:
int main () {
	List< int >			a(42);
	List< float >		b(3.14f);
	List< List< int > >	c(a);
}

//! default typess in templates
{
template < typename T = float> // = "If i don't tell you what type it is, assume it's `float`" => So we set the `default type` to be float!
class Vertex {
	public:
		Vertex(T const & x, T const & y, T const & z) : _x(x), _y(y, _z(z)) {}
		~Vertex() {}

		T const & getX() const { return this->_x; }
		T const & getY() const { return this->_y; }
		T const & getZ() const { return this->_z; }

		//etc...

	private:
		T const _x;
		T const _y;
		T const _z;

		Vertex(void); // we do the default constructor private so that the user can instanciate this class only with the paramter constructor above, when he gives 3 values for x,y,z
};

//and in that case we instanciate like:
int main() {
	Vertex<int> v1(12, 14, 25); //then T will be int
	Vertex<> 	v2(12, 14, 25); //the we use the default type which is `float` now, so the three integer vvalues will be implicitly converted to float, in order to instantiate our template class Vertex.
}

//And we can even overload the insertion operator with tempaltes:
template <typename T>
std::ostream & operator<<(std::ostream & o, Vertex<T> const & v) {
	std::cout.precision(1);
	o << setiosflags(std::ios::fixed);
	o << "Vertex( ";
	o << v.getX() << ", ";
	o << v.getY() << ", ";
	o << v.getZ() << " )";
	return o;
}

//so that if I do in the main, something like:
std::cout << v1 << std::endl;
std::cout << v2 << std::endl;

//then this would output:
Vertex(12, 14, 25);
Vertex(12.0, 14.0, 25.0);

}
}


//! STL (Standard Templates Library) && CONTAINERS
{
#include <iostream>
#include <map>
#include <vector>
#include <list>

class IOperation ;

int main() {

	// 1. LIST
	{
	std::list<int>		lst1;

	// then we can add numbers to the the list like:
	lst1.push_back(1);
	lst1.push_back(17);
	lst1.push_back(42);

	// and we can iterate to the list like:
	std::list<int>::const_iterator	it;
	std::list<int>::const_iterator	ite = lst1.end();
	// iterators are like pointers pointing to the elements of the container

	for (it = lst1.begin(); it != ite; ++it) {
		std::cout << *it << std::endl;
	}
	}

	// 2. MAPS
	std::map< std::string, IOperation* > map1;

	map1["opA"] = new OperationA; // Operation A and B are derived Classes from IOperation
	map1["opB"] = new OperationB;

	// 3. VECTORS
	std::vector<int>	v1;
	std::vector<int>	v2(42, 100);
}

//! ALGORITHMS

#include <iostream>
#include <algorithm>
#include <list>

void displayInt(int i) {
	std::cout << i << std::endl;
}

int main() {
	
	std::list<int> lst;

	lst.push_back(10);
	lst.push_back(7);
	lst.push_back(42);
	lst.push_back(8);
	lst.push_back(21);

	//and instead of the for loop before, we ca actually do:
	for_each(lst.begin(), lst.end(), displayInt);

	return 0;

}


}





CVb3d2023

